### ISSUE TITLE
EMP 1.14.3 Error syncing with website

### ISSUE THREAD

**Issue by VeeKai** [enjin/Enjin-Minecraft-Plugin#10]
Hello, after reports of new users to my website not being whitelisted and receiving their ranks I thought I better check it out. I found the following error:

`[2019-07-05 09:55:26 ERROR] An error occured while syncing with Enjin services...
java.lang.IllegalStateException: PermissionEntityEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at ru.tehkode.permissions.bukkit.PermissionsEx.callEvent(PermissionsEx.java:393) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionManager.callEvent(PermissionManager.java:697) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionEntity.callEvent(PermissionEntity.java:730) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionEntity.callEvent(PermissionEntity.java:734) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionEntity.setParentsIdentifier(PermissionEntity.java:925) ~[PermissionsEx-1.23.4.jar:?]
	at ru.tehkode.permissions.PermissionUser.addGroup(PermissionUser.java:149) ~[PermissionsEx-1.23.4.jar:?]
	at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.playerAddGroup(Permission_PermissionsEx.java:136) ~[Vault.jar:?]
	at com.enjin.bukkit.sync.BukkitInstructionHandler.addToGroup(BukkitInstructionHandler.java:54) ~[EnjinMinecraftPlugin.jar:?]
	at com.enjin.bukkit.sync.data.AddPlayerGroupInstruction.handle(AddPlayerGroupInstruction.java:8) ~[EnjinMinecraftPlugin.jar:?]
	at com.enjin.bukkit.sync.RPCPacketManager.sync(RPCPacketManager.java:134) ~[EnjinMinecraftPlugin.jar:?]
	at com.enjin.bukkit.sync.RPCPacketManager.run(RPCPacketManager.java:62) [EnjinMinecraftPlugin.jar:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]`

I don't know what it means but I believe it is the cause of my issue.

Regards,
Vk

**Comment by Favorlock** [comment]
Have you tried updating PEX to the latest version? Looks like they are calling an event and that event is conflicting with newer versions of Spigot which enforce a/sync event calls to run on certain threads. This honestly looks like something that would be their responsibility to fix.

**Comment by Favorlock** [comment]
Closing due to no reply back. Assuming the issue was resolved by updating PEX.
