### ISSUE TITLE
LuckPerms

### ISSUE THREAD

**Issue by VeeKai** [enjin/Enjin-Minecraft-Plugin#12]
I've just set up luckPerms and can not seem to get it to Sync correctly.

I'm getting this error log.

`[23:32:07] [Craft Scheduler Thread - 4/ERROR]: An error occured while syncing with Enjin services...
java.lang.IllegalStateException: Asynchronous command dispatch!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:708) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:627) ~[spigot.jar:git-Spigot-9de398a-9c887d4]
        at com.enjin.bukkit.EnjinMinecraftPlugin.dispatchConsoleCommand(EnjinMinecraftPlugin.java:426) ~[EnjinMinecraftPlugin.jar:?]
        at com.enjin.bukkit.sync.BukkitInstructionHandler.addToWhitelist(BukkitInstructionHandler.java:25) ~[EnjinMinecraftPlugin.jar:?]
        at com.enjin.bukkit.sync.data.AddWhitelistPlayerInstruction.handle(AddWhitelistPlayerInstruction.java:7) ~[EnjinMinecraftPlugin.jar:?]
        at com.enjin.bukkit.sync.RPCPacketManager.sync(RPCPacketManager.java:151) ~[EnjinMinecraftPlugin.jar:?]
        at com.enjin.bukkit.sync.RPCPacketManager.run(RPCPacketManager.java:62) [EnjinMinecraftPlugin.jar:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-9de398a-9c887d4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**Comment by Favorlock** [comment]
I've uploaded a new build at https://github.com/enjin/Enjin-Minecraft-Plugin/releases/tag/v3.5.8

This should resolve the issue.

**Comment by VeeKai** [comment]
Thanks it seems to work, I'll let you know if I run into issues.

**Comment by Favorlock** [comment]
Glad to hear. Going to close this issue. If you do run into issues just reply here or create a new issue if it appears to be a new issue.
