### ISSUE TITLE
ConcurrentModificationException: null

### ISSUE THREAD

**Issue by mibby** [enjin/Enjin-Minecraft-Plugin#13]
Java 12
Paper dev 175 (Spigot 1.14.4)
EnjinMinecraftPlugin v3.5.10

@Favorlock Came across this error in my console.
```
[20:58:23] [Craft Scheduler Thread - 214/WARN]: [EnjinMinecraftPlugin] Plugin EnjinMinecraftPlugin v3.5.10 generated an exception while executing task 241
java.util.ConcurrentModificationException: null
	at com.enjin.shaded.gson.internal.LinkedTreeMap$LinkedTreeMapIterator.nextNode(LinkedTreeMap.java:541) ~[?:?]
	at com.enjin.shaded.gson.internal.LinkedTreeMap$EntrySet$1.next(LinkedTreeMap.java:565) ~[?:?]
	at com.enjin.shaded.gson.internal.LinkedTreeMap$EntrySet$1.next(LinkedTreeMap.java:563) ~[?:?]
	at com.enjin.shaded.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:206) ~[?:?]
	at com.enjin.shaded.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145) ~[?:?]
	at com.enjin.shaded.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68) ~[?:?]
	at com.enjin.shaded.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:99) ~[?:?]
	at com.enjin.shaded.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:219) ~[?:?]
	at com.enjin.shaded.gson.Gson.toJson(Gson.java:600) ~[?:?]
	at com.enjin.shaded.gson.Gson.toJson(Gson.java:579) ~[?:?]
	at com.enjin.shaded.gson.Gson.toJson(Gson.java:534) ~[?:?]
	at com.enjin.shaded.gson.Gson.toJson(Gson.java:514) ~[?:?]
	at com.enjin.core.config.JsonConfig.save(JsonConfig.java:54) ~[?:?]
	at com.enjin.bukkit.EnjinMinecraftPlugin.saveRankUpdatesConfiguration(EnjinMinecraftPlugin.java:328) ~[?:?]
	at com.enjin.bukkit.tasks.ConfigSaver.run(ConfigSaver.java:14) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-175]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-175]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by Favorlock** [comment]
If I don't hear back in the next few days I'll assume this issue is resolved and close the this issue.
