### ISSUE TITLE
Enjin commands missing / broken

### ISSUE THREAD

**Issue by mibby** [enjin/Enjin-Minecraft-Plugin#28]
## Prerequisites

Please answer the following questions before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I didn't use ```/reload```

## Expected Behavior

@Favorlock 

I have vote rewards that run Enjin commands from console when players reach a certain vote total in-game. It uses the command ``enjin addpoints %player% 1000``. This command doesn't seem to exist anymore with EnjinMinecraftPlugin v3.6.0 with the specified changelog;

> Reworked command system for Spigot.

## Current Behavior

Command doesn't exist.

![link](https://i.imgur.com/zFMLorA.png)

## Steps to Reproduce 

Please provide detailed steps for reproducing the issue if applicable.

1. Try to run command as OP/Admin from in-game & from console
2. Doesn't work

## Context

You removed commands and never re-added them? Others seem to have reported the same thing on the Spigot forums.
https://www.spigotmc.org/threads/enjin-cms-donationcraft-plugin.116821/page-30#post-3921967
https://www.spigotmc.org/threads/enjin-cms-donationcraft-plugin.116821/page-30#post-3925502

### Server Platform

- [ ] Spigot
- [x] Paper
- [ ] Sponge
- [ ] Bungee
- [ ] Other:

Version: Tuinity dev 393 (Paper 1.16.3)

### Java

Version: Oracle JDK 14.0.2

## Enjin Report

What else is broken?
```
[01:12:13] [Server thread/INFO]: mibby issued server command: /enjin report
[01:12:17] [Server thread/INFO]: Generating report, please wait...
[01:12:17] [Craft Scheduler Thread - 44 - EnjinMinecraftPlugin/WARN]: [EnjinMinecraftPlugin] Plugin EnjinMinecraftPlugin v3.6.0 generated an exception while executing task 11950
java.lang.NullPointerException: null
	at com.enjin.bukkit.report.ReportPublisher.addPluginVersionAndStatus(ReportPublisher.java:135) ~[?:?]
	at com.enjin.bukkit.report.ReportPublisher.addEconomyPlugin(ReportPublisher.java:118) ~[?:?]
	at com.enjin.bukkit.report.ReportPublisher.addVaultIntegrations(ReportPublisher.java:106) ~[?:?]
	at com.enjin.bukkit.report.ReportPublisher.addIntegrations(ReportPublisher.java:93) ~[?:?]
	at com.enjin.bukkit.report.ReportPublisher.run(ReportPublisher.java:68) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Tuinity-"102d60b"]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.3.jar:git-Tuinity-"102d60b"]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Tuinity-"102d60b"]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by mibby** [comment]
This is what it looks like on v3.5.14.

![link](https://i.imgur.com/31QFHCQ.png)

**Comment by nexlemav** [comment]
Doubt it was a bug but an intended removal. "/enjin addpoints" has been an important feature to server admins for many years. Having it removed without notice is extremely devastating to many server owners that use this feature as a game play reward.
