### ISSUE TITLE
Offline Vote and placeholder

### ISSUE THREAD

**Issue by Feldmarschall** [enjin/Enjin-Minecraft-Plugin#7]
Spigot: git-Spigot-df0eb25-f2757f9 (MC: 1.14.2)
Enjin-Plugin: 3.5.6

1. placeholder doesnt work. %enjinminecraftplugin_points%

2. Error when voting offline.

`[10:22:41] [Server thread/ERROR]: Could not pass event VotifierEvent to EnjinMinecraftPlugin v3.5.6
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-df0eb25-f2757f9]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-df0eb25-f2757f9]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [server.jar:git-Spigot-df0eb25-f2757f9]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [server.jar:git-Spigot-df0eb25-f2757f9]
at com.vexsoftware.votifier.net.VoteReceiver$1.run(VoteReceiver.java:182) [votifier-1.9.jar:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [server.jar:git-Spigot-df0eb25-f2757f9]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-df0eb25-f2757f9]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [server.jar:git-Spigot-df0eb25-f2757f9]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [server.jar:git-Spigot-df0eb25-f2757f9]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [server.jar:git-Spigot-df0eb25-f2757f9]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [server.jar:git-Spigot-df0eb25-f2757f9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
at com.enjin.bukkit.listeners.VotifierListener.voteRecieved(VotifierListener.java:51) ~[?:?]
at sun.reflect.GeneratedMethodAccessor911.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-df0eb25-f2757f9]
... 11 more
>
[10:22:42] [Server thread/ERROR]: Could not pass event VotifierEvent to EnjinMinecraftPlugin v3.5.6
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-df0eb25-f2757f9]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-df0eb25-f2757f9]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [server.jar:git-Spigot-df0eb25-f2757f9]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [server.jar:git-Spigot-df0eb25-f2757f9]
at com.vexsoftware.votifier.net.VoteReceiver$1.run(VoteReceiver.java:182) [votifier-1.9.jar:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) [server.jar:git-Spigot-df0eb25-f2757f9]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [server.jar:git-Spigot-df0eb25-f2757f9]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1008) [server.jar:git-Spigot-df0eb25-f2757f9]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [server.jar:git-Spigot-df0eb25-f2757f9]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [server.jar:git-Spigot-df0eb25-f2757f9]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [server.jar:git-Spigot-df0eb25-f2757f9]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
at com.enjin.bukkit.listeners.VotifierListener.voteRecieved(VotifierListener.java:51) ~[?:?]
at sun.reflect.GeneratedMethodAccessor911.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-df0eb25-f2757f9]
... 11 more`

**Comment by Favorlock** [comment]
I'm not sure what you mean by the placeholder mentioned in number 1. EMP 3.x doesn't have anything like that. As for the second issue that may already be fixed as I made some changes to the voting listener a few weeks back, but a new build hasn't been published yet, but I'll compare against the latest code-base to make sure.

**Comment by Favorlock** [comment]
Ok, so this shouldn't be an issue with the updates I had made. Once a new version is released this should be fixed.
