### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by ReflxctionDev** [enjin/Enjin-Minecraft-Plugin#8]
First, I apologize for the unintelligible issue title, as I can't manage to understand how the issue is produced.

Prior to installing EMP v3.5.6 on a PaperSpigot 1.14.2 server, the following error appears in console on fixed intervals (an updating scheduler I assume.)

`> [10:29:25 WARN]: [EnjinMinecraftPlugin] Task #586229 for EnjinMinecraftPlugin v3.5.6 generated an exception
java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
at com.enjin.bukkit.modules.impl.SignStatsModule.updateHead(SignStatsModule.java:242) ~[?:?]
at com.enjin.bukkit.modules.impl.SignStatsModule$3.run(SignStatsModule.java:212) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[paper1142.jar:git-Paper-81]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[paper1142.jar:git-Paper-81]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1129) ~[paper1142.jar:git-Paper-81]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[paper1142.jar:git-Paper-81]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[paper1142.jar:git-Paper-81]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[paper1142.jar:git-Paper-81]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by Favorlock** [comment]
I see what's going on. I'll take a look soon and fix it.

**Comment by Favorlock** [comment]
I've made some changes that remove a reference to a deprecated class, so things should work now that I'm using the appropriate method of getting certain information.

**Comment by ReflxctionDev** [comment]
Thanks, are there any CI builds I could get the fix from?

**Comment by Favorlock** [comment]
We don't have a CI, but I do upload builds on GitHub before they  are published on the Spigot forums and Enjin control panel. You can find such builds at https://github.com/enjin/Enjin-Minecraft-Plugin/releases. The latest build (3.5.7) on that page is yet to be published and contains changes related to this issue. If things still aren't working please let me know.

**Comment by ReflxctionDev** [comment]
The plugin seems to be working just fine now, the error no longer appears. Thanks for the quick fix!
